import { AlertCircle, Download, ImageIcon, Share } from "lucide-react";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { imageHelpers } from "@/lib/image-helpers";
import type { ProviderTiming } from "@/lib/image-types";
import { cn } from "@/lib/utils";
import { Stopwatch } from "./Stopwatch";
import {
	Tooltip,
	TooltipContent,
	TooltipProvider,
	TooltipTrigger,
} from "./ui/tooltip";

interface ImageDisplayProps {
	provider: string;
	image: string | null | undefined;
	timing?: ProviderTiming;
	failed?: boolean;
	fallbackIcon?: React.ReactNode;
	enabled?: boolean;
	modelId: string;
}

export function ImageDisplay({
	provider,
	image,
	timing,
	failed,
	fallbackIcon,
	modelId,
}: ImageDisplayProps) {
	const [isZoomed, setIsZoomed] = useState(false);

	useEffect(() => {
		if (isZoomed) {
			window.history.pushState({ zoomed: true }, "");
		}

		const handleEscape = (e: KeyboardEvent) => {
			if (e.key === "Escape" && isZoomed) {
				setIsZoomed(false);
			}
		};

		const handlePopState = () => {
			if (isZoomed) {
				setIsZoomed(false);
			}
		};

		if (isZoomed) {
			document.addEventListener("keydown", handleEscape);
			window.addEventListener("popstate", handlePopState);
		}

		return () => {
			document.removeEventListener("keydown", handleEscape);
			window.removeEventListener("popstate", handlePopState);
		};
	}, [isZoomed]);

	const handleImageClick = (e: React.MouseEvent) => {
		if (image) {
			e.stopPropagation();
			setIsZoomed(true);
		}
	};

	const handleActionClick = (
		e: React.MouseEvent,
		imageData: string,
		provider: string,
	) => {
		e.stopPropagation();
		imageHelpers.shareOrDownload(imageData, provider).catch((error) => {
			console.error("Failed to share/download image:", error);
		});
	};

	return (
		<>
			<div
				className={cn(
					"group relative h-full w-full rounded-lg bg-zinc-50",
					image && !failed && "cursor-pointer",
					(!image || failed) && "border-1 border-zinc-100",
				)}
				onClick={handleImageClick}
			>
				{(image || failed) && (
					<div className="absolute top-2 left-2 z-10 flex max-w-[75%] items-center gap-2 rounded-full bg-white/95 px-3 py-1.5 shadow-sm">
						<TooltipProvider>
							<Tooltip delayDuration={100}>
								<TooltipTrigger asChild>
									<Label className="min-w-0 grow truncate text-gray-900 text-xs font-medium">
										{imageHelpers.formatModelId(modelId)}
									</Label>
								</TooltipTrigger>
								<TooltipContent>
									<p>{modelId}</p>
								</TooltipContent>
							</Tooltip>
						</TooltipProvider>
					</div>
				)}
				{image && !failed ? (
					<>
						<img
							alt={`Generated by ${provider}`}
							className="h-full w-full rounded-lg object-cover"
							src={`data:image/png;base64,${image}`}
						/>
						<Button
							className="absolute bottom-3 left-3 rounded-full shadow-lg transition-opacity sm:opacity-0 sm:group-hover:opacity-100"
							onClick={(e) => handleActionClick(e, image, provider)}
							size="icon"
							variant="secondary"
						>
							<span className="sm:hidden">
								<Share className="h-4 w-4" />
							</span>
							<span className="hidden sm:block">
								<Download className="h-4 w-4" />
							</span>
						</Button>
						{timing?.elapsed && (
							<div className="absolute right-3 bottom-3 rounded-full bg-black/70 px-3 py-1.5 shadow-lg backdrop-blur-sm">
								<span className="font-medium text-white/90 text-xs">
									{(timing.elapsed / 1000).toFixed(1)}s
								</span>
							</div>
						)}
					</>
				) : (
					<div className="absolute inset-0 flex flex-col items-center justify-center">
						{failed ? (
							fallbackIcon || <AlertCircle className="h-8 w-8 text-red-500" />
						) : image ? (
							<>
								<img
									alt={`Generated by ${provider}`}
									className="h-full w-full rounded-lg object-cover"
									src={`data:image/png;base64,${image}`}
								/>
								<Button
									className="absolute bottom-3 left-3 rounded-full shadow-lg transition-opacity sm:opacity-0 sm:group-hover:opacity-100"
									onClick={(e) => handleActionClick(e, image, provider)}
									size="icon"
									variant="secondary"
								>
									<span className="sm:hidden">
										<Share className="h-4 w-4" />
									</span>
									<span className="hidden sm:block">
										<Download className="h-4 w-4" />
									</span>
								</Button>
							</>
						) : timing?.startTime ? (
							<>
								<Stopwatch startTime={timing.startTime} />
							</>
						) : (
							<ImageIcon className="h-12 w-12 text-zinc-300" />
						)}
					</div>
				)}
			</div>

			{isZoomed &&
				image &&
				createPortal(
					<div
						className="fixed inset-0 z-50 flex min-h-[100dvh] w-screen cursor-pointer items-center justify-center bg-black/90"
						onClick={() => setIsZoomed(false)}
					>
						<img
							alt={`Generated by ${provider}`}
							className="max-h-[90dvh] max-w-[90vw] rounded-lg object-contain"
							onClick={(e) => e.stopPropagation()}
							src={`data:image/png;base64,${image}`}
						/>
					</div>,
					document.body,
				)}
		</>
	);
}
